---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminsurance
  labels:
       app: term
spec:
  replicas: 1
  template:
    metadata:
      name: terminsurance-pod
      labels:
        app: term
    spec:
      containers:
        - name: terminsurance
          image: sharan77/terminsurance
  selector:
    matchLabels:
      app: term

---
apiVersion: v1
kind: Service
metadata:
  name: terminsuranceservice
spec:
  type : NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30099
  selector:
    app: term